all:
	gcc guloso.c -Wall -std=c99 -o ex

clear:
	rm ex

run:
	./ex

teste1:
	./ex < ../testes/10.txt

teste2:
	./ex < ../testes/100.txt

teste3:
	./ex < ../testes/1000.txt

teste4:
	./ex < ../testes/5000.txt

teste5:
	./ex < ../testes/10000.txt