all:
	gcc bruta.c -Wall -std=c99 -o bruta
run:
	./bruta

clean:
	rm bruta.o bruta

teste1:
	./bruta < ../testes/10.txt

teste2:
	./bruta < ../testes/100.txt

teste3:
	./bruta < ../testes/1000.txt

teste4:
	./bruta < ../testes/5000.txt

teste5:
	./bruta < ../testes/10000.txt